cache:
  directories:
    - $HOME/.m2

language: java

services:
  - docker

stages:
  - deploy

install: skip

jobs:
  include:
    - stage: deploy
      name: "deploying"
      script:
        - deploy.sh